// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ForgetPasswordDto
 */
export interface ForgetPasswordDto {
	/**
	 * @type {number}
	 * @memberof ForgetPasswordDto
	 */
	tid: number;
	/**
	 * @type {object}
	 * @memberof ForgetPasswordDto
	 */
	answer: {
		[x: string]: string;
	};
	/**
	 * @type {string}
	 * @memberof ForgetPasswordDto
	 */
	new_pwd: string;
}
