// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
	/**
	 * @type {string}
	 * @memberof RegisterDto
	 */
	name: string;
	/**
	 * @type {string}
	 * @memberof RegisterDto
	 */
	description: string;
	/**
	 * @type {string}
	 * @memberof RegisterDto
	 */
	email: string;
	/**
	 * @type {string}
	 * @memberof RegisterDto
	 */
	password: string;
	/**
	 * @type {string}
	 * @memberof RegisterDto
	 */
	sex: string;
	/**
	 * @type {object}
	 * @memberof RegisterDto
	 */
	question: {
		[x: string]: string;
	};
	/**
	 * @type {object}
	 * @memberof RegisterDto
	 */
	birthday: string;
}
