[global]

expire=604800000

[global.db]

uri="mongodb://root:123456789Sd!@localhost:27017/?authMechanism=DEFAULT&authSource=admin"

[global.redis]

host="localhost"
port=6379
db=1
password="123456789Sd1"
expired=604800

[global.jwt]

secret="xBuYxme6eYaAi7ayBB8R"
issuer="Taco-issuer"
expire="1y"

[global.rabbitmq]

uri="amqp://guest:guest@localhost:5672"
enableControllerDiscovery=true

[global.rabbitmq.notice]
exchange="system.notice"

[global.rabbitmq.notice.routing_key]
friends_notice="notice.friends"
groups_notice="notice.groups"
system_notice="notice.system"

[global.rabbitmq.rpc]
createQueueIfNotExists=true
exchange='system.call'

[http]

port=3000

[system]
size=10
[system.notice]
# 意味着每页只有十个
size=10
[system.request]
salt="x7faqgjw"
size=10
expire=604800000

[request.removeRequest]
exchange='system.call'
queue='system.call.request'
routingKey='request.remove'
[request.addRequest]
exchange='system.call'
queue='system.call.request'
routingKey='request.add'