version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app_dockerfile
    ports:
       - "3000:3000"
       - "3001:3001"
    env_file:
      - .env
    networks:
      rice:
        ipv4_address: 172.18.0.2
  micro_service:
    build: 
      context: .
      dockerfile: micro_service_dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      rice:
        ipv4_address: 172.18.0.3
networks:
  rice:
    external: true
