version: '3.8'
services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REIDS_PASSWORD=123456789Sd!
      - ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=123456789Sd!
      - MONGODB_REPLICA_SET_KEY=123456789Sd
  rabbitmq:
    image: rabbitmq:management
    # environment:
    #   - RABBITMQ_SECURE_PASSWORD=no
    #   - RABBITMQ_LOGS=-
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
  restful:
    build:
        context: .
        dockerfile: ./docker/restful-dockerfile
    ports:
        - '3000:3000'
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=1
        - REDIS_PASSWD=123456789Sd!
        - MONGO_PATH=mongodb://mongo:27017/Taco?authMechanism=DEFAULT&authSource=admin
        - RABBITMQ_PATH=amqp://guest:guest@rabbitmq:5672

    depends_on:
        - redis
        - mongo
        - rabbitmq
