// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AddFriendResponse
 */
export interface AddFriendResponse {
	/**
	 * @type {number}
	 * @memberof AddFriendResponse
	 */
	code: number;
	/**
	 * @type {string}
	 * @memberof AddFriendResponse
	 */
	message: string;
	/**
	 * @type {object}
	 * @memberof AddFriendResponse
	 */
	data: object;
}
