// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GroupMember } from '../../';

/**
 * @export
 * @interface UpdateMemberProfileResponse
 */
export interface UpdateMemberProfileResponse {
	/**
	 * @type {number}
	 * @memberof UpdateMemberProfileResponse
	 */
	code?: number;
	/**
	 * @type {string}
	 * @memberof UpdateMemberProfileResponse
	 */
	message?: string;
	/**
	 * @type {GroupMember}
	 * @memberof UpdateMemberProfileResponse
	 */
	data?: GroupMember;
}
