// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateGroupProfileResponseData
 */
export interface UpdateGroupProfileResponseData {
	/**
	 * @type {string}
	 * @memberof UpdateGroupProfileResponseData
	 */
	gid: string;
	/**
	 * @type {string}
	 * @memberof UpdateGroupProfileResponseData
	 */
	name: string;
	/**
	 * @type {string}
	 * @memberof UpdateGroupProfileResponseData
	 */
	description: string;
	/**
	 * @type {Array<string>}
	 * @memberof UpdateGroupProfileResponseData
	 */
	notices: Array<string>;
	/**
	 * @type {Array<string>}
	 * @memberof UpdateGroupProfileResponseData
	 */
	banner: Array<string>;
}
