// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from '../../';

/**
 * @export
 * @interface UpdateUserProfileResponse
 */
export interface UpdateUserProfileResponse {
	/**
	 * @type {number}
	 * @memberof UpdateUserProfileResponse
	 */
	code: number;
	/**
	 * @type {string}
	 * @memberof UpdateUserProfileResponse
	 */
	message: string;
	/**
	 * @type {Profile}
	 * @memberof UpdateUserProfileResponse
	 */
	data: Profile;
}
