http:
  port: 3000
ws:
  port: 3000
redis:
  host: localhost
  port: 6379
  db: 1
  password: 123456789Sd!
  expired: 604800
  namespace:
    notice:
      expired: 604800
db:
  host: 127.0.0.1
  port: 27017
  db: Taco
  auth_db: ?authMechanism=DEFAULT&authSource=admin
  user: root
  password: root
jwt:
  secret: xBuYxme6eYaAi7ayBB8R
  issuer: Taco-issuer
  expire: 1y
rabbitmq:
  uri: amqp://gust:guest@localhost:5672
  notice:
    exchange: system.notice
    routing_key:
      friends_notice: notice.friends
      groups_notice: notice.groups
      system_notice: notice.system