// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CanChangeProfile
 */
export interface CanChangeProfile {
	/**
	 * @type {string}
	 * @memberof CanChangeProfile
	 */
	nick: string;
	/**
	 * @type {string}
	 * @memberof CanChangeProfile
	 */
	description: string;
	/**
	 * @type {string}
	 * @memberof CanChangeProfile
	 */
	birthday: string;
	/**
	 * @type {string}
	 * @memberof CanChangeProfile
	 */
	email: string;
}
