// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Friend
 */
export interface Friend {
	/**
	 * @type {string}
	 * @memberof Friend
	 */
	tid: string;
	/**
	 * @type {string}
	 * @memberof Friend
	 */
	nick: string;
	/**
	 * @type {string}
	 * @memberof Friend
	 */
	description: string;
	/**
	 * @type {string}
	 * @memberof Friend
	 */
	birthday: string;
	/**
	 * @type {string}
	 * @memberof Friend
	 */
	tag: string;
}
