// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GroupMember
 */
export interface GroupMember {
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	tid: string;
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	nick: string;
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	description: string;
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	birthday: string;
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	email: string;
	/**
	 * @type {string}
	 * @memberof GroupMember
	 */
	group_nick: string;
	/**
	 * @type {number}
	 * @memberof GroupMember
	 */
	level: GroupMemberLevelEnum;
	/**
	 * @type {boolean}
	 * @memberof GroupMember
	 */
	bot: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum GroupMemberLevelEnum {
	NUMBER_11 = 11,
	NUMBER_10 = 10,
	NUMBER_1 = 1,
}
