// tslint:disable
/**
 * next-taco
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface MinimumGroupProfile
 */
export interface MinimumGroupProfile {
	/**
	 * @type {string}
	 * @memberof MinimumGroupProfile
	 */
	name: string;
	/**
	 * @type {string}
	 * @memberof MinimumGroupProfile
	 */
	description: string;
	/**
	 * @type {Array<string>}
	 * @memberof MinimumGroupProfile
	 */
	banner: Array<string>;
	/**
	 * 群员总数
	 * @type {string}
	 * @memberof MinimumGroupProfile
	 */
	total: string;
}
